micronaut:
  application:
    name: codereview-backend

  server:
    port: 8080
    netty:
      parent:
        loom-carrier: true
      thread-selection: blocking

  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public

  security:
    authentication: cookie
    redirect:
      login-success: /
      login-failure: /
    cookie:
      cookie-secure: false
      cookie-same-site: Lax

    intercept-url-map:
      - pattern: /**
        access: [isAnonymous()]
github:
  token: ${GITHUB_TOKEN:}

datasources:
  default:
    url: jdbc:duckdb:${DUCKDB_PATH}
    driver-class-name: org.duckdb.DuckDBDriver
    dialect: ANSI
    schema-generate: NONE
